### ISSUE TITLE
This package has no license

### ISSUE THREAD

**Issue by liamkeily** [ScriptFUSION/StaticClass#1]
[Enlightn](https://www.laravel-enlightn.com/) advises against using this package, and packages like https://github.com/ScriptFUSION/ByteFormatter that depend on it, because it doesn't have a license.

<img width="746" alt="image" src="https://user-images.githubusercontent.com/2040842/196890191-9262dd8f-293a-4ea6-bd50-fe6087a41fab.png">

**Comment by Bilge** [comment]
I suppose there is no reason not to MIT this.
